### ISSUE TITLE
It doesn't work on my server

### ISSUE THREAD

**Issue by ksgfk** [IchorDev/Latch#36]
`[Server thread/ERROR] [Sponge]: Could not pass ChangeBlockEvent$Break$Impl to Plugin{id=latch, name=latch, version=0.5.0, description=An extensive container locking plugin., url=https://github.com/IchorPowered/Latch, source=.\mods\Latch-0.5.0-S7.1.0.jar}
java.lang.NullPointerException: null
	at com.meronat.latch.entities.LockManager.getLock(LockManager.java:59) ~[LockManager.class:?]
	at com.meronat.latch.listeners.ChangeBlockListener.onBreakBlockByPlayer(ChangeBlockListener.java:197) ~[ChangeBlockListener.class:?]
	at org.spongepowered.common.event.listener.BreakListener_ChangeBlockListener_onBreakBlockByPlayer341.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2705-7.1.0-BETA-3361]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3361]
	at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:443) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3361]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3361]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:447) [SpongeEventManager.class:1.12.2-2705-7.1.0-BETA-3361]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:225) [SpongeImpl.class:1.12.2-2705-7.1.0-BETA-3361]
	at org.spongepowered.common.event.tracking.TrackingUtil.iterateChangeBlockEvents(TrackingUtil.java:606) [TrackingUtil.class:1.12.2-2705-7.1.0-BETA-3361]
	at org.spongepowered.common.event.tracking.TrackingUtil.processBlockCaptures(TrackingUtil.java:499) [TrackingUtil.class:1.12.2-2705-7.1.0-BETA-3361]
	at org.spongepowered.common.event.tracking.TrackingUtil.processBlockCaptures(TrackingUtil.java:454) [TrackingUtil.class:1.12.2-2705-7.1.0-BETA-3361]
	at org.spongepowered.common.event.tracking.phase.packet.InteractionPacketState.unwind(InteractionPacketState.java:130) [InteractionPacketState.class:1.12.2-2705-7.1.0-BETA-3361]
	at org.spongepowered.common.event.tracking.phase.packet.InteractionPacketState.unwind(InteractionPacketState.java:72) [InteractionPacketState.class:1.12.2-2705-7.1.0-BETA-3361]
	at org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:265) [PhaseTracker.class:1.12.2-2705-7.1.0-BETA-3361]
	at org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:565) [PhaseContext.class:1.12.2-2705-7.1.0-BETA-3361]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:94) [PacketUtil.class:1.12.2-2705-7.1.0-BETA-3361]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zle000(SourceFile:539) [hv$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_171]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:293) [SpongeImplHooks.class:1.12.2-2705-7.1.0-BETA-3361]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zjj000(MinecraftServer.java:3963) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]

[Server thread/ERROR] [Sponge]: Could not pass ClickInventoryEvent$Shift$Primary$Impl to Plugin{id=latch, name=latch, version=0.5.0, description=An extensive container locking plugin., url=https://github.com/IchorPowered/Latch, source=.\mods\Latch-0.5.0-S7.1.0.jar}
java.lang.NullPointerException: null
	at com.meronat.latch.entities.LockManager.getLock(LockManager.java:59) ~[LockManager.class:?]
	at com.meronat.latch.listeners.InteractBlockListener.onClickInventory(InteractBlockListener.java:91) ~[InteractBlockListener.class:?]
	at org.spongepowered.common.event.listener.ClickInventoryEventListener_InteractBlockListener_onClickInventory346.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2705-7.1.0-BETA-3361]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3361]
	at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:443) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3361]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3361]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:447) [SpongeEventManager.class:1.12.2-2705-7.1.0-BETA-3361]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:225) [SpongeImpl.class:1.12.2-2705-7.1.0-BETA-3361]
	at org.spongepowered.common.event.tracking.phase.packet.BasicInventoryPacketState.unwind(BasicInventoryPacketState.java:195) [BasicInventoryPacketState.class:1.12.2-2705-7.1.0-BETA-3361]
	at org.spongepowered.common.event.tracking.phase.packet.BasicInventoryPacketState.unwind(BasicInventoryPacketState.java:56) [BasicInventoryPacketState.class:1.12.2-2705-7.1.0-BETA-3361]
	at org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:265) [PhaseTracker.class:1.12.2-2705-7.1.0-BETA-3361]
	at org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:565) [PhaseContext.class:1.12.2-2705-7.1.0-BETA-3361]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:94) [PacketUtil.class:1.12.2-2705-7.1.0-BETA-3361]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zle000(SourceFile:539) [hv$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_171]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:293) [SpongeImplHooks.class:1.12.2-2705-7.1.0-BETA-3361]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zjj000(MinecraftServer.java:3963) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]

[Server thread/ERROR] [Sponge]: Could not pass InteractBlockEvent$Secondary$MainHand$Impl to Plugin{id=latch, name=latch, version=0.5.0, description=An extensive container locking plugin., url=https://github.com/IchorPowered/Latch, source=.\mods\Latch-0.5.0-S7.1.0.jar}
java.lang.NullPointerException: null
	at com.meronat.latch.entities.LockManager.getLock(LockManager.java:59) ~[LockManager.class:?]
	at com.meronat.latch.listeners.InteractBlockListener.onPlayerClick(InteractBlockListener.java:179) ~[InteractBlockListener.class:?]
	at org.spongepowered.common.event.listener.InteractBlockEventListener_InteractBlockListener_onPlayerClick349.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2705-7.1.0-BETA-3361]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3361]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:347) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3361]
	at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:435) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3361]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:1189) [or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.redirect$onProcessRightClickBlock$zin000(NetHandlerPlayServer.java:2410) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739) [pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) [ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) [ma.class:?]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:92) [PacketUtil.class:1.12.2-2705-7.1.0-BETA-3361]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zle000(SourceFile:539) [hv$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_171]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:293) [SpongeImplHooks.class:1.12.2-2705-7.1.0-BETA-3361]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zjj000(MinecraftServer.java:3963) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]`
Sponge version:7.1.0-BETA-3164
Forge version:14.23.4.2705

**Comment by parlough** [comment]
This is quite a strange issue. Does it always happen? When does it specifically happen? What mods do you have? I'm going to push something that may help alleviate the problem, but I'm not really sure what could be causing this. Thanks.

**Comment by vectrixdevelops** [comment]
Is this still an issue for you @ksgfk ?
